application: wokangallery
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

- url: /console.*
  script: shell.py
  login: admin

- url: /assets
  static_dir: assets

- url: /static
  static_dir: static
  expiration: 1d

- url: /admin/.*
  script: admin_main.py
  login: admin

- url: /.*
  script: main.py